In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/multilingual-speech-recognition/sample_submission.csv
/kaggle/input/competitions/multilingual-speech-recognition/train.csv
/kaggle/input/competitions/multilingual-speech-recognition/test.csv
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00000.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00019.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00088.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00071.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00084.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00001.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00031.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00094.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00061.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00027.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00057.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00081.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00018.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00096.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00039.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00036.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00017.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00078.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00099.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00079.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00045.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00053.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00060.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00023.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00003.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00055.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00059.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00090.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00087.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00062.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00089.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00083.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00009.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00005.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00014.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00091.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00026.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00092.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00067.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00050.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00068.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00034.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00037.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00040.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00065.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00012.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00011.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00013.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00069.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00016.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00015.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00049.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00020.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00052.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00054.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00074.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00030.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00066.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00002.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00085.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00098.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00086.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00025.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00072.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00093.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00021.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00048.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00043.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00075.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00064.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00007.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00022.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00038.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00097.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00080.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00076.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00024.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00008.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00058.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00070.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00004.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00095.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00029.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00035.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00032.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00010.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00042.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00051.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00073.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00047.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00077.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00063.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00044.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00056.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00046.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00006.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00041.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00028.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00033.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/test/audio_00082.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00266.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01560.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00359.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00287.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01556.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00953.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00491.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01327.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00323.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01264.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00887.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00674.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01230.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00668.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00445.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01229.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01336.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01999.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01129.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01466.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00237.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00640.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00672.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01863.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01379.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01287.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01383.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00000.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00019.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01704.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01158.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00768.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00429.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01080.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01479.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01201.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00175.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01677.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00752.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01319.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00876.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01652.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00203.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00535.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01789.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01281.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01730.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01101.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00837.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01643.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00767.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01915.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00146.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01805.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00162.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00416.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00729.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00387.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00531.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01412.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00163.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01036.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00246.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01998.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00692.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00235.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00088.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00369.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01962.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01420.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01110.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01376.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00273.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01935.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00666.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00623.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00920.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00446.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01583.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01350.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01151.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00300.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00952.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01367.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00071.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01314.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00084.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00821.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01308.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00375.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01183.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01806.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00255.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00909.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01693.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00157.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00457.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00201.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01695.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_00001.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01007.wav
/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/audio_01508.wav

In [2]:
!pip install -q transformers datasets librosa jiwer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 39.1 MB/s eta 0:00:00

In [3]:
train_df = pd.read_csv('/kaggle/input/competitions/multilingual-speech-recognition/train.csv')
test_df = pd.read_csv('/kaggle/input/competitions/multilingual-speech-recognition/test.csv')

train_df.head()

   id            audio                                               text
0   0  audio_00000.wav                      you had quoted plutarch line.
1   1  audio_00001.wav  மலையேறுதலில் வந்து பார்த்தீங்கன்னா ஜஸ்ட்டு நம்...
2   2  audio_00002.wav  to do his phd in engineering about four years ...
3   3  audio_00003.wav                          maybe he was not at home.
4   4  audio_00004.wav  BUT WE DIDN'T BREAK HIS OLD WINDOW YOU KNOW EX...

In [4]:
import librosa

BASE_PATH = "/kaggle/input/competitions/multilingual-speech-recognition/competition_data/train/"

def load_audio(filename):
    full_path = BASE_PATH + filename
    audio, sr = librosa.load(full_path, sr=16000)
    audio = librosa.util.normalize(audio)
    return audio

In [5]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)  # remove punctuation
    text = re.sub(r"\s+", " ", text).strip()
    return text

train_df['text'] = train_df['text'].apply(normalize_text)

In [6]:
from transformers import WhisperProcessor, WhisperForConditionalGeneration

model_name = "openai/whisper-small"

processor = WhisperProcessor.from_pretrained(model_name)
model = WhisperForConditionalGeneration.from_pretrained(model_name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

In [7]:
from datasets import Dataset

def prepare(example):
    audio = load_audio(example['audio'])
    
    inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
    example["input_features"] = inputs.input_features[0]
    
    labels = processor.tokenizer(example["text"]).input_ids
    example["labels"] = labels
    
    return example

dataset = Dataset.from_pandas(train_df)
dataset = dataset.map(prepare)

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [8]:
from transformers import DataCollatorForSeq2Seq

def data_collator(features):
    input_features = [torch.tensor(f["input_features"]) for f in features]
    labels = [torch.tensor(f["labels"]) for f in features]

    input_features = torch.nn.utils.rnn.pad_sequence(
        input_features, batch_first=True
    )

    labels = torch.nn.utils.rnn.pad_sequence(
        labels,
        batch_first=True,
        padding_value=-100
    )

    return {
        "input_features": input_features,
        "labels": labels
    }

In [9]:
from transformers import Seq2SeqTrainingArguments,Seq2SeqTrainer
import torch

training_args = Seq2SeqTrainingArguments(
    output_dir="./whisper",
    per_device_train_batch_size=8,
    learning_rate=1e-5,
    num_train_epochs=2,
    fp16=True,
    logging_steps=100,
    save_steps=500
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=data_collator,
)

trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=250, training_loss=1.6756167755126954, metrics={'train_runtime': 1637.6947, 'train_samples_per_second': 2.442, 'train_steps_per_second': 0.153, 'total_flos': 1.15434160128e+18, 'train_loss': 1.6756167755126954, 'epoch': 2.0})

In [10]:
from jiwer import wer

def predict(audio_path):
    audio = load_audio(audio_path)

    inputs = processor(audio, sampling_rate=16000, return_tensors="pt")
    input_features = inputs.input_features.to(model.device)

    predicted_ids = model.generate(
        input_features,
        language="en",
        task="transcribe"
    )

    transcription = processor.batch_decode(
        predicted_ids, skip_special_tokens=True
    )[0]

    return transcription

In [11]:
preds = []
refs = []

for _, row in train_df.sample(100).iterrows():
    pred = predict(row['audio'])
    preds.append(pred)
    refs.append(row['text'])

print("WER:", wer(refs, preds))

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

WER: 0.13425925925925927

In [12]:
test_df['text'] = test_df['audio'].apply(predict)

test_df['text'] = test_df['text'].apply(normalize_text)

test_df['text'] = test_df['text'].apply(lambda x: x if x.strip() != "" else "unknown")

submission = test_df[['audio', 'text']]

submission.to_csv("submission.csv", index=False)